baseURL: "https://https://shubhamchdhary.github.io//" 
title: Shubham Chaudhary
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1 
        - name: Publications
          url: publications/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: News
          url: news/
          weight: 4 
        - name: CV
          url: https://drive.google.com/file/d/1AfOAzEcz7KGx_5afz-fHFQms99SDOHyx/view?usp=sharing
          weight: 5

params:
    description: "I'm a PhD Scholar at IIIT Delhi."
    author: Shubham Chaudhary
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "May 2024"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Shubham Chaudhary
          subtitle: "Hi There!\n
                    
                    <b><br>
                    I'm currently a Ph.D. Scholar at IIIT Delhi, India in the Dept. of Computer Science & Engineering 
                    working in the areas of Edge Computing, Real-time Video Analytics, and Live Video Streaming. I work in the Network 
                    and Systems Lab, IIIT Delhi under the supervision of [**Dr. Arani Bhattacharya**](https://faculty.iiitd.ac.in/~arani/).
                     
                    <br><br>
                    I completed my Bachelors in Electrical Engineering from Kamla Nehru Institute of Technology Sultanpur, 
                    a state-owned autonomous college in Uttar Pradesh, India. I love watching movies and playing Badminton."
                
          imageUrl: "mypic_cropped.JPG"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Shubham Chaudhary
          buttons:
            - name: Projects
              url: projects/
            - name: Publications
              url: publications/
            - name: News
              url: news/
            - name: Teaching
              url: teaching/
            - name: CV
              url: https://drive.google.com/file/d/1AfOAzEcz7KGx_5afz-fHFQms99SDOHyx/view?usp=sharing

    socialIcons:
        - name: Email
          url: shubhamch@iiitd.ac.in
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=zjqLCUsAAAAJ&hl=en
        - name: LinkedIn
          url: https://www.linkedin.com/in/shubhamchdhary
        - name: GitHub
          url: https://github.com/shubhamchdhary

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Shubham Chaudhary"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
