baseURL: "https://shubhamchdhary.github.io/" 
title: Shubham Chaudhary
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: books/
          weight: 1 
        - name: Publications
          url: papers/
          weight: 2
        - name: News
          url: data/
          weight: 3
        # - name: Teaching
        #   url: courses/
        #   weight: 4 
        # - name: CV
        #   url: /tags/
        #   weight: 5
          

params:
    description: "I'm a PhD Scholar at IIIT Delhi."
    author: Shubham Chaudhary
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "May 2024"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Shubham Chaudhary
          subtitle: "Wilkommen! I am a Professor in the Institute of Romance Philology at the University of Regensburg, Germany. My research focuses specifically on Portuguese irregular verbs. I was a doctoral student of Professor Dr Dr Dr Dieter Vogelsang, in Munich, Germany, and later a doctoral student (second assistant) of Professor Walter Schoeffler-Henschell at the University of Wiesbaden, Germany."
          imageUrl: "picture.jpeg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Shubham Chaudhary
          buttons:
            - name: Projects
              url: /books/
            - name: Publications
              url: /papers/
            - name: News
              url: /data/
            # - name: Teaching
            #   url: /courses/
            # - name: CV
            #   url: /tags/

    socialIcons:
        - name: Email
          url: shubhamch@iiitd.ac.in
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=zjqLCUsAAAAJ&hl=en
        - name: LinkedIn
          url: https://www.linkedin.com/in/shubhamchdhary
        - name: GitHub
          url: https://github.com/shubhamchdhary

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Shubham Chaudhary"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
