baseURL: "https://shubhamchdhary.github.io//" 
title: Shubham Chaudhary
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

taxonomies:
    tag: tags

menu:
    main:
        - name: News
          url: news/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2 
        - name: Publications
          url: publications/
          weight: 3
        # - name: Teaching
        #   url: teaching/
        #   weight: 4
        - name: CV
          url: /cv.pdf
          weight: 4

params:
    description: "I'm a PhD Scholar at IIIT Delhi."
    author: Shubham Chaudhary
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "May 2024"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Shubham Chaudhary
          subtitle: <p align="justify">Hi There!
                    
                    <br><br>                    
                    I'm pursuing my Ph.D. at IIIT Delhi, India in the Dept. of Computer Science & Engineering 
                    working in the areas of Autonomous Driving, Edge Computing-based Video Analytics, and Live Video Streaming. 
                    I'm part of the <a href="https://faculty.iiitd.ac.in/~arani/wise/"><b>WISE Lab @ IIIT Delhi</b></a> supervised by <a href="https://faculty.iiitd.ac.in/~arani/"><b>Dr. Arani Bhattacharya</b></a>.
                    I was a visiting research scholar in the Dept. of Computer Science at Stony Brook University from July 2024 to Dec 2024 where I got the 
                    opportunity to work closely with <a href="https://www3.cs.stonybrook.edu/~arunab/"><b>Dr. Aruna Balasubramanian</b></a>.
                    
                    <br><br>
                    I completed my Bachelors in Electrical Engineering from Kamla Nehru Institute of Technology Sultanpur, 
                    a state-owned autonomous college in Uttar Pradesh, India. I watch movies and play badminton to escape from the research chores.</p>
                
          imageUrl: "mypic_cropped.JPG"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Shubham Chaudhary
          buttons:
            - name: News
              url: news/
            - name: Projects
              url: projects/
            - name: Publications
              url: publications/
            # - name: Teaching
            #   url: teaching/
            - name: CV
              url: cv.pdf

    socialIcons:
        - name: Email
          url: shubhamch@iiitd.ac.in
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=zjqLCUsAAAAJ&hl=en
        - name: LinkedIn
          url: https://www.linkedin.com/in/shubhamchdhary
        - name: GitHub
          url: https://github.com/shubhamchdhary

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Shubham Chaudhary"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
